[Refactor]Complete
mju-likelion/custard-pudding pull request #110
Opened 2024-05-07 09:56 UTC by zelkovaria

## 📝Summary
Apply 페이지와 관련한 컴포넌트 및 style을 TypeScript로 리팩토링

2024-05-08 05:19 UTC, ndaemy requested changes
1. eslint 가 정상적으로 작동하지 않고 있습니다. typescript 로 변경하는 중에 생긴 이슈같아보여요

위의 이슈 때문에 request changes 남겨둡니다

2024-05-08 05:19 UTC, ndaemy commented on src/components/CardLanyard/CardLanyard.tsx
> +  $pcHeight: string;
1. 일반 리액트 컴퍼넌트의 props naming 에 $ prefix 가 붙는 것은 일반적이지 않습니다.
2. width 나 height 는 number 타입으로 받고 나중에 styled-components 에서 px 를 붙여주는게 더 안전할 것 같아요

2024-05-08 05:19 UTC, ndaemy commented on src/components/checkPage/SmallButton.tsx
> +  disabled: boolean;
tsx 에서 boolean 타입은 optional 하게 써주면 더 편하게 사용할 수 있습니다

1. boolean 이 required 라면
  ```tsx
    // 사용처
    <SmallButton disabled />
    <SmallButton disabled={false} />
  ```

2. boolean 이 optional 이라면
  ```typescript
    // 사용처
    <SmallButton disabled />
    <SmallButton />
  ```

2024-05-08 05:19 UTC, ndaemy commented on src/components/checkPage/SmallButton.tsx
> +    ${({ theme }) => theme.typographies.SMALL_BTN_TXT};
theme 을 전부 camelCase 로 변경중인 것 같은데, 그렇다면 여기가 놓쳐진 것 같아요

2024-05-08 05:19 UTC, ndaemy commented on src/pages/Apply.tsx
> +}
ERROR_CODE 안에 SUCCESS 가 있는게 이상합니다
더 나은 naming 을 고민해 보시기 바랍니다

2024-05-08 05:19 UTC, ndaemy commented on src/pages/Apply.tsx
> +      } catch (error: unknown) {
typescript 4.4 버전부터는 error 가 원래 unknown 이므로 별도로 타입 선언을 할 필요가 없습니다
[참고 PR](https://github.com/microsoft/TypeScript/pull/41013)

2024-05-08 05:19 UTC, ndaemy commented on src/pages/Apply.tsx
> +          setIsLoading(false);
지금은 에러나는 경우에만 setIsLoading(false); 가 실행되고 있습니다. 오히려 정상적인 경우에는 loading 이 무제한으로 걸리고 있어요. 수정될 필요가 있습니다
finally 를 찾아보시는 것도 도움이 될거에요

2024-05-08 05:19 UTC, ndaemy commented on src/styles/colors.tsx
> +export const colors = { ...pink, ...background, ...white };
각각의 const 마다 blank line 을 넣고 싶은거라면, 여길 놓치셨군요 😂

2024-05-12 08:02 UTC, zelkovaria commented on src/pages/Apply.tsx
> +}
맞는 말씀이신 것 같아서 수정해뒀습니다!!피드백 감사합니다 😖

2024-05-12 08:04 UTC, zelkovaria commented on src/styles/colors.tsx
> +export const colors = { ...pink, ...background, ...white };
매의 눈이십니다요 ㅎ.ㅎ.. 🦅 추가 :완완:

2024-05-12 11:42 UTC, zelkovaria commented on src/components/checkPage/SmallButton.tsx
> +    ${({ theme }) => theme.typographies.SMALL_BTN_TXT};
아이고야 확인해보니 제가 꽤나 많이 놓쳤었네요 🥲 감사합니다 👍🏻

2024-05-12 12:58 UTC, Bhanjo reviewed
고생하셨습니다!

2024-05-12 12:58 UTC, Bhanjo commented on src/styles/colors.tsx
> +const pink = {
이 파일은 색상 정보를 가지고 있는 파일이므로 굳이 `tsx` 확장자를 쓸 이유가 없습니다

2024-05-12 12:58 UTC, Bhanjo commented on src/styles/index.tsx
> +export * from './typographies';
이걸 해석해보면 colors, size, typographies는 blue, theme.blue 두 방식으로 참조 가능할 것 같은데 맞나요?

2024-05-12 15:19 UTC, zelkovaria commented on src/styles/colors.tsx
> +const pink = {
헤헤 넹 선생림 ㅎㅁㅎ..바로 수정 :완완:

2024-05-15 05:23 UTC, zelkovaria commented on src/components/CardLanyard/CardLanyard.tsx
> +  $pcHeight: string;
1. 제가 개념이 헷갈렸던 것 같아요 ㅎ.ㅎ.. 덕분에 학습할 수 있게 되었습니다!! 감사합니다 👍🏻
2. 잘못된 값 전달 방지나 유연성 측면에서 더 안전한 게 맞을까요! 수정 완완했습니다 ( •̀ω•́ )✧

2024-05-15 05:41 UTC, zelkovaria commented on src/components/checkPage/SmallButton.tsx
> +  disabled: boolean;
오옹 default 값 추가하여 수정 완완했습니다 선생림!! 감사합니다 👍🏻

2024-05-15 05:48 UTC, zelkovaria commented on src/App.tsx
> +import { theme } from './styles/index';
헤헤 꿀팁 배워갑니다,,, 🤧

2024-05-15 06:02 UTC, zelkovaria commented on src/pages/Apply.tsx
> +          setIsLoading(false);
말씀해주신대로 반영을 해서 수정해봤읍니다 ,,,!! 여유있으실 때 확인해주시면 감사하겠습니다 선생림!!🥹👍🏻

2024-05-20 08:39 UTC, zelkovaria commented on src/styles/index.tsx
> +export * from './typographies';
네에...!!👀

2024-05-20 11:22 UTC, zelkovaria commented on package.json
> +    "@types/styled-components": "^5.1.34",
헤헤 넴 선생님!@! 감사합니다!!!!

2024-05-21 03:52 UTC, ndaemy approved these changes

2024-05-21 07:33 UTC, zelkovaria commented on src/styles/colors.ts
> +};
수정 완완입니당 👍🏻

2024-05-21 07:34 UTC, zelkovaria commented on src/styles/index.ts
> +export * from './typographies';
한 곳에서 관리하려던 의도였습니당...ㅎ

2024-05-21 07:37 UTC, merged